replicaCount: 1
image:
  repository: healthsamurai/aidboxdb
  tag: 13.2
  pullPolicy: IfNotPresent

service:
  port: 5432

user: postgres
database: {{cookiecutter.project_slug}}

persistence:
  size: 10Gi
